# NODE_URL="http://node.deviceproof.org:14265"
NODE_URL="https://node.deviceproof.org:443"
SEED="9PPMIW9MKXRBDQZKPUXYLGDNVCKLWRWQLXPGWQUYK9JNCQEQUSLAHLORWNMMKVIMJJ9PNIOTK9B9CKMOS"
DEPTH=4
MIN_WEIGHT_MAGNITUDE=14
